### ISSUE TITLE
imports

### ISSUE THREAD

**Issue by keflavich** [jdhenshaw/casa_modules#2]
https://github.com/jdhenshaw/casa_modules/blob/19dc35613d27ba14dd59c2b1ed428a354064c530/visibilities_modules.py#L1
This should be `from tasks import concat`, plus you need something like `from tp2vis import tp2vis` or `import tp2vis`, not sure which

**Comment by edoardottt** [comment]
I bet on import tp2vis

**Comment by keflavich** [comment]
not the way he's presently using it - `import tp2vis` will import the module, but `tp2vis` is being called as a function.

Also... who are you and how did you find this issue?

**Comment by edoardottt** [comment]
Just found. def tp2vis(infile, outfile, ptg, maxuv=10.0, rms=None, nvgrp=4, deconv=True, winpix=0):
But i don't know what he uses in its repo. Maybe he uses also other functions of tp2vis.
By the trend? or explore i don't remember :P

**Comment by keflavich** [comment]
well, ok, interesting that this turned up anywhere.  We're just trying to figure out how to incorporate some code written without module imports in mind into other modules...

**Comment by jdhenshaw** [comment]
fixed
